[package]
name = "nightcycle/valuesequence"
description = "Like numbersequence, except can work with any lerpable datatype"
version = "1.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
# coldfusion = "nightcycle/cold-fusion@1.0.0"
# signal = "quenty/signal@^2.0.0-canary"
math = "nightcycle/math@2.2.1"
maid = "quenty/maid@^2.0.1-canary"
graph = "nightcycle/boat-graph@^1.0.2"
